ManagerSystem/LineManager/urls.py
from django.urls import path
from . import views
app_name = 'LineManager'

urlpatterns = [
    path('', views.index.as_view(), name='index'),
    path('add', views.add.as_view(), name='add')
]

ManagerSystem/ManagerSystem/urls.py
from django.urls import path, include
from . import views
urlpatterns = [
    path('', views.index),
    path('linemanager/', include("LineManager.urls")),
    path('sign/', include("UserManager.urls")),
    path('polemanager/', include("PoleManager.urls")),
]

ManagerSystem/PoleManager/urls.py
from django.urls import path
from . import views
app_name = 'PoleManager'
urlpatterns = [
    path('', views.index.as_view(), name='index')
]

ManagerSystem/UserManager/urls.py
from django.urls import path
from . import views
app_name = 'UserManager'
urlpatterns = [

    path('signup/', views.signup.as_view(), name='signup'),
    path('signin/', views.signin.as_view(), name='signin')
]

ManagerSystem/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">台账管理系统</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li ><a href="{% url 'LineManager:index' %}">线路台账<span class="sr-only">(current)</span></a></li>
        <li ><a href="{% url 'PoleManager:index' %}">杆塔台账<span class="sr-only">(current)</span></a></li>
        <li ><a href="#">人员台账<span class="sr-only">(current)</span></a></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
          {% if userstatus %}
            <li><a href="#">{{ userstatus.username }}</a></li>
          {% else %}
            <li><a href="{% url 'UserManager:signin' %}">登录</a></li>
            <li><a href="{% url 'UserManager:signup' %}">注册</a></li>
          {% endif %} 



      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
{% for message in messages %}
    <li>{{ message }}</li>
{% endfor %}
{% block content %}

{% endblock %}
</body>
</html>

ManagerSystem/templates/line_add.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    线路名称：<input type="text" name="name">
    线路长度：<input type="text" name="length">
    电压等级：
    <select name="degree" id="">
        <option value="750kV">750kV</option>
        <option value="330kV">330kV</option>
        <option value="220kV">220kV</option>
        <option value="110kV">110kV</option>
    </select>
    <input type="submit" value="提交">
</form>
<a href="{% url 'LineManager:index' %}">返回</a>

{% endblock %}

ManagerSystem/templates/line_index.html
{% extends 'base.html' %}
{% block content %}
    这是一个线路台站管理界面
    <a href="{% url 'LineManager:add' %}">添加线路</a>

        <table border="1">
        <tr>
            <td>序号</td>
            <td>线路名称</td>
            <td>长度</td>
            <td>电压等级</td>
            <td>操作</td>
        </tr>
            {% for line in lines %}


                <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ line.0 }} </td>
                <td>{{ line.1 }}</td>
                <td>{{ line.2 }}</td>

                <form action="" method="post">
                    {% csrf_token %}
                    <input type="hidden" value="{{ line.0 }}" name="deleteid">
                    <td><input type="submit" value="删除"></td>
                </form>

                 </tr>
            {% endfor %}



        </table>
{% endblock %}

ManagerSystem/templates/pole_index.html
{% extends 'base.html' %}
{% block content %}
    这是一个线路台站管理界面
    <a href="{% url 'LineManager:add' %}">添加线路</a>

        <table border="1">
        <tr>
            <td>序号</td>
            <td>线路名称</td>
            <td>长度</td>
            <td>电压等级</td>
            <td>操作</td>
        </tr>
            {% for line in lines %}


                <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ line.0 }} </td>
                <td>{{ line.1 }}</td>
                <td>{{ line.2 }}</td>

                <form action="" method="post">
                    {% csrf_token %}
                    <input type="hidden" value="{{ line.0 }}" name="viewpole">
                    <td><input type="submit" value="查看该线路杆塔信息"></td>
                </form>
                <form action="" method="post">
                    {% csrf_token %}
                    <input type="hidden" value="{{ line.0 }}" name="addpole">
                    <td><input type="submit" value="添加杆塔"></td>
                </form>
                 </tr>
            {% endfor %}



        </table>
{% endblock %}

ManagerSystem/templates/signin.html
{% extends 'base.html' %}
{% block content %}
    <form action="" method="post">
    {% csrf_token %}
        <tr>
        <td>用户名</td>
        <input type="text" name="username" >
        </tr>
        <tr>
            <td>密码</td>
        <input type="text" name="password">
        </tr>
        <input type="submit" value="登录">
    </form>
{% endblock %}

ManagerSystem/templates/signup.html
{% extends 'base.html' %}
{% block content %}
    <form action="" method="post">
    {% csrf_token %}
        <tr>
        <td>用户名</td>
        <input type="text" name="username" >
        </tr>
        <tr>
            <td>密码</td>
            <input type="text" name="pwd1">
        </tr>
        <tr>
            <td>重复密码</td>
            <input type="text" name="pwd2">
        </tr>
        <input type="submit" value="注册">
    </form>
{% endblock %}